import { useEffect, useMemo, useState } from 'react'
import { Activity, AlertCircle, Bell, BriefcaseBusiness, CalendarDays, Check, ChevronDown, ClipboardCheck, Download, FileText, LayoutDashboard, Menu, Plus, Search, Settings, Target, Upload, Users, X } from 'lucide-react'
import './App.css'
import { supabaseEnabled } from './lib/supabase'
import { createWorkspaceRecord, listWorkspaceRecords, subscribeToWorkspaceRecords } from './repositories/workspaceRepository'

const teamMembers = [
  { name: 'Ivy', role: 'Team Member', initials: 'IV', color: 'teal' },
  { name: 'Max', role: 'Team Member', initials: 'MX', color: 'blue' },
  { name: 'Marion', role: 'Team Member', initials: 'MA', color: 'purple' },
]
const navGroups = [
  { label: 'Main', items: [['Dashboard', LayoutDashboard], ['Team', Users], ['Projects', BriefcaseBusiness], ['Tasks', ClipboardCheck], ['Updates', Activity], ['Meetings', CalendarDays], ['Announcements', Bell], ['Documents', FileText]] },
  { label: 'Reports', items: [['Team Reports', Target], ['Project Reports', BriefcaseBusiness], ['My Reports', FileText]] },
  { label: 'Settings', items: [['Settings', Settings]] },
]

function App() {
  const [currentUser, setCurrentUser] = useState(() => teamMembers.find((member) => member.name === localStorage.getItem('teamops-user')) || null)
  const [activePage, setActivePage] = useState('Dashboard')
  const [query, setQuery] = useState('')
  const [menuOpen, setMenuOpen] = useState(false)
  const [showTask, setShowTask] = useState(false)
  const [toast, setToast] = useState('')
  const [tasks, setTasks] = useState([])
  const [settings, setSettings] = useState(() => JSON.parse(localStorage.getItem('teamops-settings') || '{"emailNotifications":true,"taskReminders":true,"compactMode":false,"darkMode":false}'))
  const filteredTasks = useMemo(() => tasks.filter((task) => task.title.toLowerCase().includes(query.toLowerCase())), [query, tasks])
  const [workspaceData, setWorkspaceData] = useState(() => JSON.parse(localStorage.getItem('teamops-workspace') || '{"Projects":[],"Tasks":[],"Updates":[],"Meetings":[],"Announcements":[],"Documents":[],"Team":[]}'))
  useEffect(() => {
    if (!supabaseEnabled) return undefined
    let mounted = true
    listWorkspaceRecords().then((records) => {
      if (!mounted) return
      const grouped = records.reduce((result, record) => ({ ...result, [record.page]: [...(result[record.page] || []), record] }), {})
      setWorkspaceData((current) => ({ ...current, ...grouped }))
    }).catch(() => setToast('Unable to load shared workspace data'))
    const unsubscribe = subscribeToWorkspaceRecords(() => {
      listWorkspaceRecords().then((records) => {
        const grouped = records.reduce((result, record) => ({ ...result, [record.page]: [...(result[record.page] || []), record] }), {})
        setWorkspaceData((current) => ({ ...current, ...grouped }))
      }).catch(() => setToast('Unable to refresh shared workspace data'))
    })
    return () => { mounted = false; unsubscribe() }
  }, [])

  if (!currentUser) return <Login onLogin={(member) => { localStorage.setItem('teamops-user', member.name); setCurrentUser(member) }} />

  const createTask = (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); setTasks((current) => [...current, { title: form.get('title') }]); setShowTask(false); setToast('Task created successfully'); window.setTimeout(() => setToast(''), 2600) }
  const logout = () => { localStorage.removeItem('teamops-user'); setCurrentUser(null) }
  const updateSettings = (nextSettings) => { setSettings(nextSettings); localStorage.setItem('teamops-settings', JSON.stringify(nextSettings)); setToast('Settings saved'); window.setTimeout(() => setToast(''), 2200) }

  const addRecord = async (page, record) => { try { const sharedRecord = await createWorkspaceRecord(page, record); const savedRecord = sharedRecord || { ...record, page }; const next = { ...workspaceData, [page]: [...(workspaceData[page] || []), savedRecord] }; setWorkspaceData(next); localStorage.setItem('teamops-workspace', JSON.stringify(next)); setToast(`${page.slice(0, -1)} created successfully`); window.setTimeout(() => setToast(''), 2200) } catch { setToast(`Unable to create ${page.slice(0, -1).toLowerCase()}`) } }
  return <div className={`app-shell ${settings.darkMode ? 'dark' : ''}`}>
    <aside className={`sidebar ${menuOpen ? 'open' : ''}`}>
      <div className="brand"><div className="brand-mark"><Users size={17} /></div><div><strong>TeamOps</strong><small>Team Operations Hub</small></div></div>
      <nav>{navGroups.map((group) => <div className="nav-group" key={group.label}><span className="nav-label">{group.label}</span>{group.items.map(([label, Icon]) => <button className={`nav-item ${activePage === label ? 'active' : ''}`} key={label} onClick={() => { setActivePage(label); setMenuOpen(false) }}><Icon size={16} /><span>{label}</span></button>)}</div>)}</nav>
      <button className="profile-switcher" onClick={logout}><span className={`avatar ${currentUser.color}`}>{currentUser.initials}</span><span className="profile-copy"><strong>{currentUser.name}</strong><small>{currentUser.role}</small></span><ChevronDown size={15} /></button>
    </aside>
    <main className="main-content">
      <header className="topbar"><button className="icon-button mobile-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Open navigation"><Menu size={18} /></button><div className="page-heading"><Menu size={16} className="desktop-menu" /><div><h1>Good morning, {currentUser.name}! <span>👋</span></h1><p>Here's what's happening with your team today.</p></div></div><div className="header-actions"><label className="search"><Search size={14} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search tasks..." /></label><button className="icon-button notification" aria-label="Notifications"><Bell size={17} /></button><button className={`header-avatar ${currentUser.color}`}>{currentUser.initials}</button><button className="primary-button" onClick={() => setShowTask(true)}><Plus size={15} /> New Task</button></div></header>
      {activePage === 'Settings' ? <SettingsPage currentUser={currentUser} settings={settings} updateSettings={updateSettings} onLogout={logout} /> : activePage === 'Dashboard' ? <>
        <section className="kpi-grid">{[['Active Projects', '0', 'No projects yet', BriefcaseBusiness, 'mint'], ['Tasks Due Today', String(filteredTasks.length), filteredTasks.length ? 'Your tasks' : 'No tasks yet', CalendarDays, 'sky'], ['Overdue Tasks', '0', 'All clear', AlertCircle, 'peach'], ['Team Members', String(teamMembers.length), 'All active', Users, 'lilac']].map(([label, value, caption, Icon, tone]) => <article className="kpi-card" key={label}><div><p>{label}</p><strong>{value}</strong><small>{caption}</small></div><div className={`kpi-icon ${tone}`}><Icon size={18} /></div></article>)}</section>
        <section className="content-grid top-grid"><Card title="Projects Overview"><Empty text="No projects yet. Create your first project to start organizing your team's work." /><button className="empty-action" onClick={() => setActivePage('Projects')}><Plus size={13} /> Create project</button></Card><Card title="Tasks Summary"><div className="empty-panel"><ClipboardCheck size={23} /><strong>{tasks.length ? `${tasks.length} task${tasks.length === 1 ? '' : 's'}` : 'No tasks yet'}</strong><span>Create a task to see your team's progress here.</span></div></Card><Card title="Team Overview"><div className="member-list">{teamMembers.map((member) => <div className="member-row" key={member.name}><span className={`avatar ${member.color}`}>{member.initials}</span><div className="member-info"><strong>{member.name}</strong><span>{member.role}</span></div><Status tone="green">Active</Status></div>)}</div></Card></section>
        <section className="content-grid bottom-grid"><Card title="Upcoming Deadlines"><Empty text="No upcoming deadlines." /></Card><Card title="Recent Tasks">{filteredTasks.length ? filteredTasks.map((task) => <div className="update-row" key={task.title}><span className="avatar tiny blue">{currentUser.initials}</span><div><strong>{task.title}</strong><span>Created just now</span></div></div>) : <Empty text="Your recent tasks will appear here." />}</Card><Card title="Announcements"><Empty text="No announcements yet." /></Card></section>
      </> : <WorkspacePage page={activePage} records={workspaceData[activePage] || []} onCreate={addRecord} onBack={() => setActivePage('Dashboard')} onGenerate={() => { setToast(`${activePage} generated successfully`); window.setTimeout(() => setToast(''), 2200) }} />}
    </main>
    {showTask && <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setShowTask(false)}><form className="modal" onSubmit={createTask}><div className="modal-heading"><div><p className="eyebrow">Tasks</p><h2>Create new task</h2></div><button type="button" className="icon-button" onClick={() => setShowTask(false)} aria-label="Close"><X size={17} /></button></div><label>Task title<input name="title" required placeholder="e.g. Review dashboard concepts" /></label><label>Description<textarea name="description" placeholder="Add context for the team..." rows="3"></textarea></label><div className="modal-footer"><button type="button" className="secondary-button" onClick={() => setShowTask(false)}>Cancel</button><button className="primary-button" type="submit"><Check size={15} /> Create task</button></div></form></div>}
    {toast && <div className="toast"><Check size={16} />{toast}</div>}
  </div>
}
function Login({ onLogin }) { const [name, setName] = useState(''); const [error, setError] = useState(''); const submit = (event) => { event.preventDefault(); const member = teamMembers.find((person) => person.name.toLowerCase() === name.trim().toLowerCase()); if (member) onLogin(member); else setError('We could not find that team member. Check the name and try again.') }; return <main className="login-page"><div className="login-card"><div className="brand login-brand"><div className="brand-mark"><Users size={17} /></div><div><strong>TeamOps</strong><small>Team Operations Hub</small></div></div><p className="eyebrow">Welcome back</p><h1>Sign in to your workspace</h1><p className="login-copy">Enter your name to continue. No password or signup is required.</p><form onSubmit={submit}><label>Your name<input autoFocus value={name} onChange={(event) => { setName(event.target.value); setError('') }} placeholder="Enter your name" /></label>{error && <p className="login-error">{error}</p>}<button className="primary-button login-button" type="submit">Sign in <Plus size={15} /></button></form></div></main> }
function Card({ title, children }) { return <article className="panel"><div className="panel-heading"><h2>{title}</h2></div>{children}</article> }
function Status({ tone, children }) { return <span className={`status ${tone}`}>{children}</span> }
function Empty({ text }) { return <div className="empty-state">{text}</div> }
function SettingsPage({ currentUser, settings, updateSettings, onLogout }) {
  const [profileName, setProfileName] = useState(currentUser.name)
  const saveProfile = (event) => { event.preventDefault(); const nextUser = { ...currentUser, name: profileName.trim() || currentUser.name }; localStorage.setItem('teamops-user', nextUser.name); updateSettings(settings) }
  const downloadBackup = () => { const backup = { product: 'TeamOps', exportedAt: new Date().toISOString(), settings, currentUser }; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([JSON.stringify(backup, null, 2)], { type: 'application/json' })); link.download = 'teamops-workspace-backup.json'; link.click(); URL.revokeObjectURL(link.href) }
  const restoreBackup = (event) => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const backup = JSON.parse(reader.result); if (!backup.settings) throw new Error('Invalid backup'); updateSettings(backup.settings) } catch { window.alert('That backup file is not valid TeamOps data.') } }; reader.readAsText(file) }
  const toggle = (key) => updateSettings({ ...settings, [key]: !settings[key] })
  return <section className="settings-page"><div className="settings-intro"><div><p className="eyebrow">Workspace configuration</p><h2>Settings</h2><p>Manage your personal preferences and local TeamOps workspace.</p></div><button className="secondary-button" onClick={onLogout}>Sign out</button></div><div className="settings-grid"><form className="settings-panel" onSubmit={saveProfile}><div className="settings-heading"><div><h3>Profile</h3><p>Update the name shown across TeamOps.</p></div><span className={`avatar ${currentUser.color}`}>{currentUser.initials}</span></div><label>Display name<input value={profileName} onChange={(event) => setProfileName(event.target.value)} required /></label><button className="primary-button" type="submit"><Check size={14} /> Save profile</button></form><div className="settings-panel"><div className="settings-heading"><div><h3>Notifications</h3><p>Choose which local reminders you receive.</p></div><Bell size={18} className="settings-symbol" /></div><SettingToggle label="Email notifications" description="Updates about your workspace" checked={settings.emailNotifications} onChange={() => toggle('emailNotifications')} /><SettingToggle label="Task reminders" description="Due dates and overdue tasks" checked={settings.taskReminders} onChange={() => toggle('taskReminders')} /></div><div className="settings-panel"><div className="settings-heading"><div><h3>Appearance</h3><p>Adjust how TeamOps fits your workflow.</p></div><Settings size={18} className="settings-symbol" /></div><SettingToggle label="Compact mode" description="Use tighter spacing across lists" checked={settings.compactMode} onChange={() => toggle('compactMode')} /><SettingToggle label="Dark mode" description="Use a darker workspace theme" checked={settings.darkMode} onChange={() => toggle('darkMode')} /></div><div className="settings-panel"><div className="settings-heading"><div><h3>Workspace data</h3><p>Export or restore your local preferences.</p></div><Download size={18} className="settings-symbol" /></div><div className="data-actions"><button className="secondary-button" type="button" onClick={downloadBackup}><Download size={14} /> Backup workspace</button><label className="secondary-button file-button"><Upload size={14} /> Restore backup<input type="file" accept="application/json" onChange={restoreBackup} /></label></div><small className="settings-note">Your data stays on this device.</small></div></div></section>
}
function SettingToggle({ label, description, checked, onChange }) { return <label className="setting-toggle"><span><strong>{label}</strong><small>{description}</small></span><input type="checkbox" checked={checked} onChange={onChange} /><i></i></label> }
function WorkspacePage({ page, records, onCreate, onBack, onGenerate }) { const [showForm, setShowForm] = useState(false); const singular = page.replace(/s$/, ''); const isReport = page.includes('Reports'); const submit = (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); onCreate(page, { title: form.get('title'), description: form.get('description'), createdAt: new Date().toLocaleDateString() }); setShowForm(false) }; return <section className="workspace-page"><div className="workspace-heading"><div><p className="eyebrow">TeamOps workspace</p><h2>{page}</h2><p>Keep your team's {page.toLowerCase()} organized in one local workspace.</p></div><div className="workspace-actions">{isReport ? <button className="primary-button" onClick={onGenerate}><Target size={15} /> Generate report</button> : <button className="primary-button" onClick={() => setShowForm(true)}><Plus size={15} /> Add {singular}</button>}<button className="secondary-button" onClick={onBack}>Dashboard</button></div></div>{records.length ? <div className="record-grid">{records.map((record, index) => <article className="record-card" key={`${record.title}-${index}`}><div className="record-icon"><FileText size={17} /></div><div><h3>{record.title}</h3><p>{record.description || `Created ${record.createdAt}`}</p><small>{record.createdAt}</small></div></article>)}</div> : <div className="workspace-empty"><div className="placeholder-icon"><FileText size={23} /></div><h3>No {page.toLowerCase()} yet</h3><p>Create your first {singular.toLowerCase()} to start organizing your team.</p>{!isReport && <button className="primary-button" onClick={() => setShowForm(true)}><Plus size={15} /> Add {singular}</button>}</div>}{showForm && <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setShowForm(false)}><form className="modal" onSubmit={submit}><div className="modal-heading"><div><p className="eyebrow">{page}</p><h2>Add {singular}</h2></div><button type="button" className="icon-button" onClick={() => setShowForm(false)} aria-label="Close"><X size={17} /></button></div><label>Name or title<input name="title" required placeholder={`Enter ${singular.toLowerCase()} name`} /></label><label>Description<textarea name="description" rows="4" placeholder="Add details..." /></label><div className="modal-footer"><button type="button" className="secondary-button" onClick={() => setShowForm(false)}>Cancel</button><button className="primary-button" type="submit"><Check size={15} /> Save</button></div></form></div>}</section> }
export default App
