create table if not exists public.workspace_records (
  id bigint generated by default as identity primary key,
  page text not null check (page in ('Team', 'Projects', 'Tasks', 'Updates', 'Meetings', 'Announcements', 'Documents')),
  title text not null check (char_length(trim(title)) > 0),
  description text,
  created_at timestamptz not null default now()
);

alter table public.workspace_records enable row level security;

create policy "workspace records are readable by team"
on public.workspace_records for select to anon using (true);

create policy "workspace records can be created by team"
on public.workspace_records for insert to anon with check (true);

alter publication supabase_realtime add table public.workspace_records;
